definitions:
  models.GeozoneModel:
    properties:
      count:
        type: integer
      geozones:
        items:
          $ref: '#/definitions/models.geozone'
        type: array
    type: object
  models.Location:
    properties:
      lat:
        type: number
      long:
        type: number
    type: object
  models.Order:
    properties:
      branch_id:
        type: string
      co_id:
        type: string
      creator_type_id:
        type: string
      fare_id:
        type: string
      from_address:
        type: string
      from_location:
        $ref: '#/definitions/models.Location'
        type: object
      phone_number:
        type: string
      products:
        $ref: '#/definitions/models.Product'
        type: object
      to_address:
        type: string
      to_location:
        $ref: '#/definitions/models.Location'
        type: object
      user_id:
        type: string
    type: object
  models.Product:
    properties:
      id:
        type: string
      name:
        type: string
      price:
        type: number
      quantity:
        type: number
    type: object
  models.ResponseError:
    properties:
      error:
        type: object
    type: object
  models.geozone:
    properties:
      geometry:
        type: string
      id:
        type: string
      name:
        type: string
      parent_id:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /v1/geozones/:
    get:
      consumes:
      - application/json
      description: Get Geozones
      parameters:
      - description: Parent ID
        in: query
        name: parent_id
        type: string
      - description: PAGE
        in: query
        name: page
        type: integer
      - description: PAGE
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GeozoneModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Get Geozones
      tags:
      - geo
  /v1/order//:
    post:
      consumes:
      - application/json
      description: API for creating order
      parameters:
      - description: order
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/models.Order'
      produces:
      - application/json
      responses:
        "200": {}
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Create Order
      tags:
      - order
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
