definitions:
  models.CreateOrder:
    properties:
      branch_id:
        example: a010f178-da52-4373-aacd-e477d871e27a
        type: string
      co_id:
        example: a010f178-da52-4373-aacd-e477d871e27a
        type: string
      creator_type_id:
        example: a010f178-da52-4373-aacd-e477d871e27a
        type: string
      fare_id:
        example: a010f178-da52-4373-aacd-e477d871e27a
        type: string
      from_address:
        example: Hamid Olimjon maydoni 10A dom 40-kvartira
        type: string
      from_location:
        $ref: '#/definitions/models.Location'
        type: object
      phone_number:
        example: "998998765432"
        type: string
      products:
        items:
          $ref: '#/definitions/models.productModel'
        type: array
      to_address:
        example: Hamid Olimjon maydoni 10A dom 40-kvartira
        type: string
      to_location:
        $ref: '#/definitions/models.Location'
        type: object
      user_id:
        example: a010f178-da52-4373-aacd-e477d871e27a
        type: string
    type: object
  models.GeozoneModel:
    properties:
      count:
        type: integer
      geozones:
        items:
          $ref: '#/definitions/models.geozone'
        type: array
    type: object
  models.GetOrder:
    properties:
      branch_id:
        example: a010f178-da52-4373-aacd-e477d871e27a
        type: string
      co_id:
        example: a010f178-da52-4373-aacd-e477d871e27a
        type: string
      creator_type_id:
        example: a010f178-da52-4373-aacd-e477d871e27a
        type: string
      fare_id:
        example: a010f178-da52-4373-aacd-e477d871e27a
        type: string
      from_address:
        example: Hamid Olimjon maydoni 10A dom 40-kvartira
        type: string
      from_location:
        $ref: '#/definitions/models.Location'
        type: object
      id:
        example: 701dc270-0adc-4d00-ae78-4f2f78d794cc
        type: string
      phone_number:
        example: "998998765432"
        type: string
      products:
        items:
          $ref: '#/definitions/models.getOrderProductModel'
        type: array
      status_id:
        example: 52f248b4-23a0-4350-80b7-1704eaff6c8c
        type: string
      to_address:
        example: Hamid Olimjon maydoni 10A dom 40-kvartira
        type: string
      to_location:
        $ref: '#/definitions/models.Location'
        type: object
      user_id:
        example: a010f178-da52-4373-aacd-e477d871e27a
        type: string
    type: object
  models.GetOrders:
    properties:
      count:
        type: integer
      orders:
        items:
          $ref: '#/definitions/models.getOrderModel'
        type: array
    type: object
  models.Location:
    properties:
      lat:
        example: 40.123
        type: number
      long:
        example: 60.123
        type: number
    type: object
  models.ResponseError:
    properties:
      error:
        type: object
    type: object
  models.ResponseOK:
    properties:
      message:
        type: object
    type: object
  models.geozone:
    properties:
      geometry:
        type: string
      id:
        type: string
      name:
        type: string
      parent_id:
        type: string
    type: object
  models.getOrderModel:
    properties:
      branch_id:
        example: a010f178-da52-4373-aacd-e477d871e27a
        type: string
      co_id:
        example: a010f178-da52-4373-aacd-e477d871e27a
        type: string
      creator_type_id:
        example: a010f178-da52-4373-aacd-e477d871e27a
        type: string
      fare_id:
        example: a010f178-da52-4373-aacd-e477d871e27a
        type: string
      from_address:
        example: Hamid Olimjon maydoni 10A dom 40-kvartira
        type: string
      from_location:
        $ref: '#/definitions/models.Location'
        type: object
      id:
        example: 701dc270-0adc-4d00-ae78-4f2f78d794cc
        type: string
      phone_number:
        example: "998998765432"
        type: string
      status_id:
        example: 52f248b4-23a0-4350-80b7-1704eaff6c8c
        type: string
      to_address:
        example: Hamid Olimjon maydoni 10A dom 40-kvartira
        type: string
      to_location:
        $ref: '#/definitions/models.Location'
        type: object
      user_id:
        example: a010f178-da52-4373-aacd-e477d871e27a
        type: string
    type: object
  models.getOrderProductModel:
    properties:
      id:
        type: string
      name:
        example: Choyxona Osh
        type: string
      price:
        example: 25000
        type: number
      quantity:
        example: 2
        type: number
      total_amount:
        type: number
    type: object
  models.productModel:
    properties:
      name:
        example: Choyxona Osh
        type: string
      price:
        example: 25000
        type: number
      quantity:
        example: 2
        type: number
    type: object
info:
  contact: {}
  license: {}
paths:
  /v1/geozones/:
    get:
      consumes:
      - application/json
      description: Get Geozones
      parameters:
      - description: Parent ID
        in: query
        name: parent_id
        type: string
      - description: PAGE
        in: query
        name: page
        type: integer
      - description: PAGE
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GeozoneModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Get Geozones
      tags:
      - geo
  /v1/order:
    get:
      consumes:
      - application/json
      description: API for getting orders
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetOrders'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Get Orders
      tags:
      - order
  /v1/order/:
    post:
      consumes:
      - application/json
      description: API for creating order
      parameters:
      - description: order
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/models.CreateOrder'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseOK'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Create Order
      tags:
      - order
  /v1/order/{order_id}:
    get:
      consumes:
      - application/json
      description: API for getting order
      parameters:
      - description: order_id
        in: path
        name: order_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetOrder'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Get Order
      tags:
      - order
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
