// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fare.proto

package fare_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Fare struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DeliveryTime         string   `protobuf:"bytes,3,opt,name=delivery_time,json=deliveryTime,proto3" json:"delivery_time,omitempty"`
	PricePerKm           uint64   `protobuf:"varint,4,opt,name=price_per_km,json=pricePerKm,proto3" json:"price_per_km,omitempty"`
	MinPrice             uint64   `protobuf:"varint,5,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MinDistance          uint64   `protobuf:"varint,6,opt,name=min_distance,json=minDistance,proto3" json:"min_distance,omitempty"`
	IsActive             bool     `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            string   `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fare) Reset()         { *m = Fare{} }
func (m *Fare) String() string { return proto.CompactTextString(m) }
func (*Fare) ProtoMessage()    {}
func (*Fare) Descriptor() ([]byte, []int) {
	return fileDescriptor_af2909dcbc3131d2, []int{0}
}

func (m *Fare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fare.Unmarshal(m, b)
}
func (m *Fare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fare.Marshal(b, m, deterministic)
}
func (m *Fare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fare.Merge(m, src)
}
func (m *Fare) XXX_Size() int {
	return xxx_messageInfo_Fare.Size(m)
}
func (m *Fare) XXX_DiscardUnknown() {
	xxx_messageInfo_Fare.DiscardUnknown(m)
}

var xxx_messageInfo_Fare proto.InternalMessageInfo

func (m *Fare) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Fare) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Fare) GetDeliveryTime() string {
	if m != nil {
		return m.DeliveryTime
	}
	return ""
}

func (m *Fare) GetPricePerKm() uint64 {
	if m != nil {
		return m.PricePerKm
	}
	return 0
}

func (m *Fare) GetMinPrice() uint64 {
	if m != nil {
		return m.MinPrice
	}
	return 0
}

func (m *Fare) GetMinDistance() uint64 {
	if m != nil {
		return m.MinDistance
	}
	return 0
}

func (m *Fare) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *Fare) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Fare) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Fare) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*Fare)(nil), "genproto.Fare")
}

func init() {
	proto.RegisterFile("fare.proto", fileDescriptor_af2909dcbc3131d2)
}

var fileDescriptor_af2909dcbc3131d2 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xd0, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x80, 0x61, 0x5a, 0xeb, 0xda, 0x8e, 0xd5, 0x43, 0x40, 0x0c, 0x88, 0x50, 0xf5, 0xd2, 0x93,
	0x1e, 0x7c, 0x82, 0x4a, 0x11, 0x16, 0x2f, 0x4b, 0xf1, 0xe4, 0x25, 0xc4, 0x76, 0x94, 0xc1, 0x4d,
	0xb6, 0xa4, 0xb1, 0xe0, 0x33, 0xf9, 0x92, 0x4b, 0xa6, 0xe9, 0x6d, 0xe6, 0xff, 0x08, 0x84, 0x01,
	0xf8, 0xd2, 0x0e, 0x1f, 0x47, 0x77, 0xf0, 0x07, 0x91, 0x7f, 0xa3, 0xe5, 0xe9, 0xfe, 0x3f, 0x85,
	0xec, 0x55, 0x3b, 0x14, 0x97, 0x90, 0x6e, 0x5b, 0x99, 0x54, 0x49, 0x5d, 0x74, 0xe9, 0xb6, 0x15,
	0x02, 0x32, 0xab, 0x0d, 0xca, 0x94, 0x0b, 0xcf, 0xe2, 0x01, 0x2e, 0x06, 0xdc, 0xd3, 0x8c, 0xee,
	0x4f, 0x79, 0x32, 0x28, 0x4f, 0x18, 0xcb, 0x35, 0xbe, 0x93, 0x41, 0x51, 0x41, 0x39, 0x3a, 0xea,
	0x51, 0x8d, 0xe8, 0xd4, 0x8f, 0x91, 0x59, 0x95, 0xd4, 0x59, 0x07, 0xdc, 0x76, 0xe8, 0xde, 0x8c,
	0xb8, 0x81, 0xc2, 0x90, 0x55, 0x5c, 0xe4, 0x29, 0x73, 0x6e, 0xc8, 0xee, 0xc2, 0x2e, 0xee, 0xa0,
	0x0c, 0x38, 0xd0, 0xe4, 0xb5, 0xed, 0x51, 0x6e, 0xd8, 0xcf, 0x0d, 0xd9, 0x36, 0xa6, 0xf0, 0x9e,
	0x26, 0xa5, 0x7b, 0x4f, 0x33, 0xca, 0xb3, 0x2a, 0xa9, 0xf3, 0x2e, 0xa7, 0xa9, 0xe1, 0x5d, 0xdc,
	0x02, 0xf4, 0x0e, 0xb5, 0xc7, 0x41, 0x69, 0x2f, 0x73, 0xfe, 0x60, 0x11, 0x4b, 0xe3, 0x03, 0xff,
	0x8e, 0xc3, 0xca, 0xc5, 0xc2, 0xb1, 0x2c, 0x3c, 0xe0, 0x1e, 0x23, 0xc3, 0xc2, 0xb1, 0x34, 0xfe,
	0xe5, 0xfa, 0xe3, 0x6a, 0xbd, 0xdc, 0x53, 0x38, 0xa7, 0x9a, 0xd0, 0xcd, 0xd4, 0xe3, 0xe7, 0x86,
	0xdb, 0xf3, 0x31, 0x00, 0x00, 0xff, 0xff, 0x20, 0x37, 0xae, 0x53, 0x65, 0x01, 0x00, 0x00,
}
