image: docker:latest

pipelines:
  branches:
    master:
      - step:
          name: Production DB migrations
          image: migrate/migrate
          script:
            - source .build_info
            - /migrate -path=migrations/ -database="$DELEVER_DATABASEURL&x-migrations-table=migrations_$APP" up
      - step:
          name: Deploy to Prod
          services:
            - docker
          script:
            - apk update && apk add make && apk add openssh
            - docker login $DELEVER_REGISTRY --username $DELEVER_DOCKER_USERNAME --password $DELEVER_DOCKER_PASSWORD
            - make build-image TAG=$BITBUCKET_BUILD_NUMBER
            - make push-image  TAG=$BITBUCKET_BUILD_NUMBER
            - source .build_info
            - ssh delever@$DELEVER_PROD_HOST 'docker service update --with-registry-auth --image '$DELEVER_REGISTRY'/'$APP':'$BITBUCKET_BUILD_NUMBER' delever_'$APP''


