image: docker:19.03.8
pipelines:
  branches:
    master:
    - step:
        image: migrate/migrate
        name: Production DB migrations
        script:
        - source .build_info
        - /migrate -path=migrations/ -database="$DELEVER_DATABASEURL&x-migrations-table=migrations_$APP"
          up
    - step:
        name: Deploy to Prod
        script:
        - apk update && apk add make && apk add openssh
        - docker login $REGISTRY --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        - make build-image TAG=$BITBUCKET_BUILD_NUMBER REGISTRY=$REGISTRY
        - make push-image  TAG=$BITBUCKET_BUILD_NUMBER REGISTRY=$REGISTRY
        - source .build_info
        - ssh delever@$DELEVER_PROD_HOST 'docker service update --with-registry-auth
          --image '$REGISTRY'/'$APP':'$BITBUCKET_BUILD_NUMBER' delever_'$APP''
        services:
        - docker
    staging:
    - step:
        image: migrate/migrate
        name: Test DB migrations
        script:
        - source .build_info
        - /migrate -path=migrations/ -database="$DELEVER_TEST_DATABASEURL&x-migrations-table=migrations_$APP"
          up
    - step:
        name: Deploy to Stating
        script:
        - apk update && apk add make && apk add openssh
        - docker login $REGISTRY --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        - make build-image TAG=$BITBUCKET_BUILD_NUMBER ENV_TAG=test REGISTRY=$REGISTRY
        - make push-image  TAG=$BITBUCKET_BUILD_NUMBER ENV_TAG=test REGISTRY=$REGISTRY
        - source .build_info
        - ssh delever@$DELEVER_TEST_HOST 'docker service update --with-registry-auth
          --image '$REGISTRY'/'$APP':'$BITBUCKET_BUILD_NUMBER' delever_'$APP''
        services:
        - docker
