version: '3'

services:
  database:
    image: postgres:12.0
    container_name: ${POSTGRES_HOST}
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PORT
    networks:
      - app-network
    ports:
      - 5433:${POSTGRES_PORT}

  redis:
    image: redis:5.0.6-alpine
    container_name: ${REDIS_HOST}
    restart: always
    networks:
      - app-network
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  app:
    image: app-test-image:latest
    container_name: app-test-container
    build:
      context: .
      dockerfile: deployments/dev/Dockerfile
    restart: "no"
    depends_on:
      - database
      - redis
    volumes:
      - $PWD:/go/src/bitbucket.org/alien_soft/${APP}
    entrypoint: /bin/sh /go/src/bitbucket.org/alien_soft/${APP}/scripts/dev/entrypoint.test.sh
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - REDIS_HOST
      - REDIS_PORT
      - APP
      - RPC_PORT=:8051
    networks:
      - app-network
    ports:
      - 8050:8050
volumes:
  pgdata:
    driver: local
networks:
  app-network:
    external: true
