// Code generated by protoc-gen-go. DO NOT EDIT.
// source: distributor.proto

package courier_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Distributor struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Status               bool     `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Distributor) Reset()         { *m = Distributor{} }
func (m *Distributor) String() string { return proto.CompactTextString(m) }
func (*Distributor) ProtoMessage()    {}
func (*Distributor) Descriptor() ([]byte, []int) {
	return fileDescriptor_c518e33639ca565d, []int{0}
}

func (m *Distributor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Distributor.Unmarshal(m, b)
}
func (m *Distributor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Distributor.Marshal(b, m, deterministic)
}
func (m *Distributor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Distributor.Merge(m, src)
}
func (m *Distributor) XXX_Size() int {
	return xxx_messageInfo_Distributor.Size(m)
}
func (m *Distributor) XXX_DiscardUnknown() {
	xxx_messageInfo_Distributor.DiscardUnknown(m)
}

var xxx_messageInfo_Distributor proto.InternalMessageInfo

func (m *Distributor) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Distributor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Distributor) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Distributor) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *Distributor) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type DistributorFare struct {
	DistributorId        string   `protobuf:"bytes,1,opt,name=distributor_id,json=distributorId,proto3" json:"distributor_id,omitempty"`
	FareId               string   `protobuf:"bytes,2,opt,name=fare_id,json=fareId,proto3" json:"fare_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistributorFare) Reset()         { *m = DistributorFare{} }
func (m *DistributorFare) String() string { return proto.CompactTextString(m) }
func (*DistributorFare) ProtoMessage()    {}
func (*DistributorFare) Descriptor() ([]byte, []int) {
	return fileDescriptor_c518e33639ca565d, []int{1}
}

func (m *DistributorFare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributorFare.Unmarshal(m, b)
}
func (m *DistributorFare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributorFare.Marshal(b, m, deterministic)
}
func (m *DistributorFare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributorFare.Merge(m, src)
}
func (m *DistributorFare) XXX_Size() int {
	return xxx_messageInfo_DistributorFare.Size(m)
}
func (m *DistributorFare) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributorFare.DiscardUnknown(m)
}

var xxx_messageInfo_DistributorFare proto.InternalMessageInfo

func (m *DistributorFare) GetDistributorId() string {
	if m != nil {
		return m.DistributorId
	}
	return ""
}

func (m *DistributorFare) GetFareId() string {
	if m != nil {
		return m.FareId
	}
	return ""
}

func init() {
	proto.RegisterType((*Distributor)(nil), "genproto.Distributor")
	proto.RegisterType((*DistributorFare)(nil), "genproto.DistributorFare")
}

func init() { proto.RegisterFile("distributor.proto", fileDescriptor_c518e33639ca565d) }

var fileDescriptor_c518e33639ca565d = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x41, 0x4b, 0x86, 0x40,
	0x10, 0x86, 0xd1, 0xbe, 0xcf, 0x74, 0x22, 0xa3, 0x21, 0x6a, 0x09, 0x02, 0x11, 0x02, 0x4f, 0x75,
	0xe8, 0x17, 0x14, 0x11, 0x78, 0xcc, 0x63, 0x17, 0x59, 0xdd, 0xa9, 0xf6, 0x90, 0x2b, 0xb3, 0x63,
	0xc7, 0x7e, 0x7b, 0xb8, 0x5a, 0x9f, 0xb7, 0xf7, 0x7d, 0x5e, 0x96, 0x7d, 0x06, 0xce, 0x8d, 0xf5,
	0xc2, 0xb6, 0x9b, 0xc4, 0xf1, 0xdd, 0xc8, 0x4e, 0x1c, 0xa6, 0x1f, 0x34, 0x84, 0x54, 0xfe, 0xc0,
	0xc9, 0xf3, 0x61, 0xc6, 0x1c, 0x62, 0x6b, 0x54, 0x54, 0x44, 0x55, 0xd6, 0xc4, 0xd6, 0x20, 0xc2,
	0x6e, 0xd0, 0x5f, 0xa4, 0xe2, 0x40, 0x42, 0xc6, 0x0b, 0xd8, 0x8f, 0x9f, 0x6e, 0x20, 0x75, 0x14,
	0xe0, 0x52, 0xf0, 0x12, 0x12, 0x2f, 0x5a, 0x26, 0xaf, 0x76, 0x45, 0x54, 0xa5, 0xcd, 0xda, 0xf0,
	0x06, 0xa0, 0x67, 0xd2, 0x42, 0xa6, 0xd5, 0xa2, 0xf6, 0xe1, 0x49, 0xb6, 0x92, 0x47, 0x29, 0x5f,
	0xe1, 0x6c, 0xf3, 0xff, 0x8b, 0x66, 0xc2, 0x5b, 0xc8, 0x37, 0xc6, 0xed, 0xbf, 0xcf, 0xe9, 0x86,
	0xd6, 0x06, 0xaf, 0xe0, 0xf8, 0x5d, 0x33, 0xcd, 0xfb, 0x62, 0x97, 0xcc, 0xb5, 0x36, 0x4f, 0xd7,
	0x6f, 0xea, 0xef, 0xbc, 0xfb, 0xde, 0x4d, 0x6c, 0x89, 0x5b, 0x4f, 0xfc, 0x6d, 0x7b, 0xea, 0x92,
	0x80, 0x1f, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x09, 0x66, 0xce, 0xb3, 0x14, 0x01, 0x00, 0x00,
}
