// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package order_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Location struct {
	Long                 float32  `protobuf:"fixed32,1,opt,name=long,proto3" json:"long,omitempty"`
	Lat                  float32  `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLong() float32 {
	if m != nil {
		return m.Long
	}
	return 0
}

func (m *Location) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

type Order struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BranchId             string                `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	FromLocation         *Location             `protobuf:"bytes,3,opt,name=from_location,json=fromLocation,proto3" json:"from_location,omitempty"`
	FromAddress          string                `protobuf:"bytes,4,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToLocation           *Location             `protobuf:"bytes,5,opt,name=to_location,json=toLocation,proto3" json:"to_location,omitempty"`
	ToAddress            string                `protobuf:"bytes,6,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	PhoneNumber          string                `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	CourierId            *wrappers.StringValue `protobuf:"bytes,8,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	FareId               string                `protobuf:"bytes,9,opt,name=fare_id,json=fareId,proto3" json:"fare_id,omitempty"`
	StatusId             string                `protobuf:"bytes,10,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	CreatedAt            string                `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Description          string                `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	CoId                 string                `protobuf:"bytes,13,opt,name=co_id,json=coId,proto3" json:"co_id,omitempty"`
	CreatorTypeId        string                `protobuf:"bytes,14,opt,name=creator_type_id,json=creatorTypeId,proto3" json:"creator_type_id,omitempty"`
	UserId               string                `protobuf:"bytes,15,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Products             []*Product            `protobuf:"bytes,16,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetBranchId() string {
	if m != nil {
		return m.BranchId
	}
	return ""
}

func (m *Order) GetFromLocation() *Location {
	if m != nil {
		return m.FromLocation
	}
	return nil
}

func (m *Order) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *Order) GetToLocation() *Location {
	if m != nil {
		return m.ToLocation
	}
	return nil
}

func (m *Order) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *Order) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Order) GetCourierId() *wrappers.StringValue {
	if m != nil {
		return m.CourierId
	}
	return nil
}

func (m *Order) GetFareId() string {
	if m != nil {
		return m.FareId
	}
	return ""
}

func (m *Order) GetStatusId() string {
	if m != nil {
		return m.StatusId
	}
	return ""
}

func (m *Order) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Order) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Order) GetCoId() string {
	if m != nil {
		return m.CoId
	}
	return ""
}

func (m *Order) GetCreatorTypeId() string {
	if m != nil {
		return m.CreatorTypeId
	}
	return ""
}

func (m *Order) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Order) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity             float32  `protobuf:"fixed32,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	TotalAmount          float32  `protobuf:"fixed32,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Product) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetTotalAmount() float32 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func init() {
	proto.RegisterType((*Location)(nil), "genproto.Location")
	proto.RegisterType((*Order)(nil), "genproto.Order")
	proto.RegisterType((*Product)(nil), "genproto.Product")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x4d, 0x8f, 0xd3, 0x40,
	0x0c, 0x86, 0xd5, 0x6c, 0x3f, 0x12, 0xa7, 0xdd, 0x5d, 0x06, 0x04, 0xd1, 0xf2, 0xa1, 0x6e, 0x0f,
	0xa8, 0x17, 0x52, 0xb4, 0x7b, 0xe0, 0xc0, 0xa9, 0xdc, 0x22, 0x21, 0x40, 0x01, 0x71, 0xe0, 0x12,
	0x4d, 0x33, 0xd3, 0x6e, 0xa4, 0x74, 0x1c, 0x26, 0x0e, 0xa8, 0x57, 0x7e, 0x19, 0x3f, 0x0d, 0x8d,
	0x27, 0xed, 0x22, 0x21, 0x6e, 0xf6, 0x63, 0xe7, 0xf5, 0x3b, 0xae, 0x0b, 0x31, 0x5a, 0xa5, 0x6d,
	0xda, 0x58, 0x24, 0x14, 0xe1, 0x4e, 0x1b, 0x8e, 0xae, 0x5e, 0xec, 0x10, 0x77, 0xb5, 0x5e, 0x71,
	0xb6, 0xe9, 0xb6, 0xab, 0x9f, 0x56, 0x36, 0x8d, 0xb6, 0xad, 0xef, 0x5c, 0xbc, 0x86, 0xf0, 0x3d,
	0x96, 0x92, 0x2a, 0x34, 0x42, 0xc0, 0xb0, 0x46, 0xb3, 0x4b, 0x06, 0xf3, 0xc1, 0x32, 0xc8, 0x39,
	0x16, 0x97, 0x70, 0x56, 0x4b, 0x4a, 0x02, 0x46, 0x2e, 0x5c, 0xfc, 0x1e, 0xc2, 0xe8, 0xa3, 0x9b,
	0x25, 0xce, 0x21, 0xa8, 0x14, 0x77, 0x47, 0x79, 0x50, 0x29, 0xf1, 0x14, 0xa2, 0x8d, 0x95, 0xa6,
	0xbc, 0x2b, 0x2a, 0xc5, 0x5f, 0x44, 0x79, 0xe8, 0x41, 0xa6, 0xc4, 0x1b, 0x98, 0x6d, 0x2d, 0xee,
	0x8b, 0xba, 0x9f, 0x96, 0x9c, 0xcd, 0x07, 0xcb, 0xf8, 0x46, 0xa4, 0x47, 0xab, 0xe9, 0xd1, 0x47,
	0x3e, 0x75, 0x8d, 0x27, 0x57, 0xd7, 0xc0, 0x79, 0x21, 0x95, 0xb2, 0xba, 0x6d, 0x93, 0x21, 0x0b,
	0xc7, 0x8e, 0xad, 0x3d, 0x12, 0xb7, 0x10, 0x13, 0xde, 0x2b, 0x8f, 0xfe, 0xab, 0x0c, 0x84, 0x27,
	0xdd, 0xe7, 0x00, 0x84, 0x27, 0xd5, 0x31, 0xab, 0x46, 0x84, 0x47, 0xcd, 0x6b, 0x98, 0x36, 0x77,
	0x68, 0x74, 0x61, 0xba, 0xfd, 0x46, 0xdb, 0x64, 0xe2, 0xc7, 0x32, 0xfb, 0xc0, 0x48, 0xbc, 0x05,
	0x28, 0xb1, 0xb3, 0x95, 0xb6, 0xee, 0xc1, 0x21, 0x4f, 0x7d, 0x96, 0xfa, 0x85, 0xa7, 0xc7, 0x85,
	0xa7, 0x9f, 0xc9, 0x56, 0x66, 0xf7, 0x55, 0xd6, 0x9d, 0xce, 0xa3, 0xbe, 0x3f, 0x53, 0xe2, 0x09,
	0x4c, 0xb6, 0xd2, 0x6a, 0xf7, 0x65, 0xc4, 0xd2, 0x63, 0x97, 0x66, 0xbc, 0xc5, 0x96, 0x24, 0x75,
	0xad, 0x2b, 0x81, 0xdf, 0xa2, 0x07, 0x99, 0x72, 0xa6, 0x4b, 0xab, 0x25, 0x69, 0x55, 0x48, 0x4a,
	0x62, 0x6f, 0xba, 0x27, 0x6b, 0x12, 0x73, 0x88, 0x95, 0x6e, 0x4b, 0x5b, 0x35, 0xbc, 0x88, 0xa9,
	0xf7, 0xfc, 0x17, 0x12, 0x0f, 0x61, 0x54, 0xa2, 0x53, 0x9e, 0x71, 0x6d, 0x58, 0x62, 0xa6, 0xc4,
	0x4b, 0xb8, 0x60, 0x0d, 0xb4, 0x05, 0x1d, 0x1a, 0xf6, 0x74, 0xce, 0xe5, 0x59, 0x8f, 0xbf, 0x1c,
	0x1a, 0xed, 0x3d, 0x77, 0xad, 0x7f, 0xed, 0x85, 0xf7, 0xec, 0xd2, 0x4c, 0x89, 0x57, 0x10, 0x36,
	0x16, 0x55, 0x57, 0x52, 0x9b, 0x5c, 0xce, 0xcf, 0x96, 0xf1, 0xcd, 0x83, 0xfb, 0xed, 0x7f, 0xf2,
	0x95, 0xfc, 0xd4, 0xb2, 0xf8, 0x35, 0x80, 0x49, 0x4f, 0xff, 0x39, 0x22, 0x01, 0x43, 0x23, 0xf7,
	0xba, 0xbf, 0x1f, 0x8e, 0xc5, 0x15, 0x84, 0xdf, 0x3b, 0x69, 0xa8, 0xa2, 0x03, 0x9f, 0x4d, 0x90,
	0x9f, 0x72, 0xf1, 0x08, 0x46, 0x8d, 0xad, 0x4a, 0xcd, 0x77, 0x11, 0xe4, 0x3e, 0x71, 0xbf, 0x1e,
	0x21, 0xc9, 0xba, 0x90, 0x7b, 0xec, 0x0c, 0xf1, 0x49, 0x04, 0x79, 0xcc, 0x6c, 0xcd, 0xe8, 0x5d,
	0xf2, 0xed, 0xf1, 0xd1, 0xe2, 0x8a, 0xff, 0x3b, 0x45, 0xab, 0xed, 0x8f, 0xaa, 0xd4, 0x9b, 0x31,
	0xc3, 0xdb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x88, 0x8b, 0x3a, 0xb8, 0x53, 0x03, 0x00, 0x00,
}
