-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgj/OjMVIQXcRIwLvd
/RCttzsqx+FOliYksfp7ZxlZMw+gCgYIKoZIzj0DAQehRANCAATdnE6Ace1NlLIU
ZxexkzRBYD2Bbmi3m8/UX636t/5dlX81klX540bBXq6iTCJw+MQJwP4sjy9uazw1
tfrNoMxh
-----END PRIVATE KEY-----